export const GET_TRIVIA_QUESTIONS = "GET_TRIVIA_QUESTIONS";
export const GET_TRIVIA_QUESTIONS_SUCCESS = "GET_TRIVIA_QUESTIONS_SUCCESS";
export const GET_TRIVIA_QUESTIONS_FAIL = "GET_TRIVIA_QUESTIONS_FAIL";
export const SAVE_USER_RESPONSE = "SAVE_USER_RESPONSE";
